# Site settings
title: Colby Dehart
email: colbydehart@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://colbydehart.com" # the base hostname & protocol for your site
twitter_username: colbydehart
github_username:  colbydehart

highlighter: pygments

paginate: 10
paginate_path: "/:num"

permalink: /:title

# Build settings
markdown: kramdown

# Prose stuff
prose:
  rooturl: '_posts'
  siteurl: 'http://www.colbydehart.com'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name "title"
        field:
          element: "text"
          value: "title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
